CREATE TABLE elections(
	id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	topic VARCHAR(255) NOT NULL,

	PRIMARY KEY(id)
);

CREATE TABLE candidates(
	id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	election_id BIGINT NOT NULL,
	name VARCHAR(255) NOT NULL,

	PRIMARY KEY(id),
	FOREIGN KEY(election_id) REFERENCES elections(id), -- TODO: ON DELETE CASCADE
	UNIQUE(election_id, name)
);