micronaut.application.name=CrowdChoice
micronaut.server.port=7000

flyway.datasources.default.enabled=true

datasources.default.url=jdbc:postgresql://localhost:5432/crowdchoice
datasources.default.username=postgres
datasources.default.password=postgres
